"""Minimal stubs for the highspy modeling API used by admin.shift_solver."""

from typing import Any, Iterable, Union

class highs_linear_expression:
    def __add__(
        self, other: Union[highs_var, highs_linear_expression, float]
    ) -> highs_linear_expression: ...
    def __radd__(
        self, other: Union[highs_var, highs_linear_expression, float]
    ) -> highs_linear_expression: ...
    def __sub__(
        self, other: Union[highs_var, highs_linear_expression, float]
    ) -> highs_linear_expression: ...
    def __mul__(self, other: float) -> highs_linear_expression: ...
    def __rmul__(self, other: float) -> highs_linear_expression: ...
    def __le__(
        self, other: Union[highs_var, highs_linear_expression, float]
    ) -> highs_linear_expression: ...
    def __ge__(
        self, other: Union[highs_var, highs_linear_expression, float]
    ) -> highs_linear_expression: ...

class highs_var:
    def __add__(
        self, other: Union[highs_var, highs_linear_expression, float]
    ) -> highs_linear_expression: ...
    def __radd__(
        self, other: Union[highs_var, highs_linear_expression, float]
    ) -> highs_linear_expression: ...
    def __sub__(
        self, other: Union[highs_var, highs_linear_expression, float]
    ) -> highs_linear_expression: ...
    def __mul__(self, other: float) -> highs_linear_expression: ...
    def __rmul__(self, other: float) -> highs_linear_expression: ...
    def __le__(
        self, other: Union[highs_var, highs_linear_expression, float]
    ) -> highs_linear_expression: ...
    def __ge__(
        self, other: Union[highs_var, highs_linear_expression, float]
    ) -> highs_linear_expression: ...
    def __eq__(self, other: object) -> highs_linear_expression: ...  # type: ignore[override]

class HighsModelStatus:
    kOptimal: HighsModelStatus
    kInfeasible: HighsModelStatus
    kTimeLimit: HighsModelStatus

class SolutionStatus:
    def __int__(self) -> int: ...

kSolutionStatusFeasible: SolutionStatus

class HighsInfo:
    primal_solution_status: int

class Highs:
    def silent(self) -> None: ...
    def setOptionValue(self, option: str, value: Any) -> Any: ...
    def addBinary(self) -> highs_var: ...
    def addVariable(self, lb: float = ..., ub: float = ...) -> highs_var: ...
    def addConstr(self, expr: highs_linear_expression) -> Any: ...
    def qsum(
        self, items: Iterable[Union[highs_var, highs_linear_expression]]
    ) -> highs_linear_expression: ...
    def maximize(self, obj: highs_linear_expression) -> Any: ...
    def getModelStatus(self) -> HighsModelStatus: ...
    def getInfo(self) -> HighsInfo: ...
    def val(self, var: highs_var) -> float: ...
